// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jojzsppxyjqjvmqbjwkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvanpzcHB4eWpxanZtcWJqd2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTYyMTYsImV4cCI6MjA1NzY5MjIxNn0.QiOj__KG_UgJHXgfa2JVL_OJaV8phPIAUyAmpUIjv1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);